### ISSUE TITLE
Mist renderer setting stops working when traveling the world

### ISSUE THREAD

**Issue by Fireztonez** [ApacheTechSolutions/ApacheTech.VintageMods.AccessibilityTweaks#5]
**Game version:** 1.16.5
**Mod Version:** 2.3.0
**SP/MP:** Single-Player (Didn't test on MP)

**Issue:** When I turn off the Mist rendering at my base and go away from my base, walking few hundred blocks away, the mist start to be visible again. I open back the setting menu and it is still supposed to be disabled looking at the setting, if I click back on the option to toggle off the disabled rendering, the mist are automatically disabled again (Basically the options is inversed every time you travel further). If I get back to my base, the mist will be there again so I always have to toggle that every time, it is a bit annoying.

**Intended behavior:** When you turn off the mist it should be off everywhere in the world.

**Comment by ApacheTech** [comment]
Thanks for the report. I'll have to have a look into this in a lot more detail, and see what's going on. The game has about three different ways of accessing/changing the same information, and it's never consistent. I've patched the most obvious paths. I'll have to dig around and see what's changing, and why.

**Comment by ApacheTech** [comment]
**Developer Notes:**

Current patch:

```csharp
        /// <summary>
        ///     Applies a <see cref="HarmonyPostfix"/> patch to the "UpdateAmbient" method in <see cref="AmbientManager"/>.
        /// </summary>
        /// <param name="__instance">The instance of <see cref="AmbientManager"/> this patch has been applied to.</param>
        [HarmonyPostfix]
        [HarmonyPatch(typeof(AmbientManager), "UpdateAmbient")]
        public static void Patch_AmbientManager_UpdateAmbient_Postfix(AmbientManager __instance)
        {
            const float minValue = 0.001f;
            if (!Settings.FogEnabled)
            {
                __instance.BlendedFogDensity = Math.Min(__instance.BlendedFogDensity, minValue);
                __instance.BlendedFogMin = Math.Min(__instance.BlendedFogMin, __instance.BlendedFogDensity);
            }

            if (Settings.MistEnabled) return;
            __instance.Base.FlatFogYPos = WeightedFloat.New(0, 0);
            __instance.Base.FlatFogDensity = WeightedFloat.New(0, 0);
            __instance.BlendedFlatFogYOffset = 0;
            __instance.BlendedFlatFogYPosForShader = -30f;
            __instance.BlendedFlatFogDensity = Math.Min(__instance.BlendedFlatFogDensity, minValue);
        }
```

It might be better to push the mist up above 1024 Y pos, into the cloud layer, than try to push it under the world. It's also worth looking at whether I can switch it off within the shader registry instead... then it doesn't matter what the inputs actually are. The shader just won't render it. However, this may mean hacking the shader strings in the same way as I did with the glitch effects. This would make it far less robust for future updates, and potentially cause the Black Screen of Death effect if shader code is changed within the game while using the mod. The latter would not be easily fixable outside of a hotfix that disables this particular feature.

A third approach would be to patch the `BlendedFloat` class itself, and determine whether the instance is a mist value; returning `0f` as a static value if it is. This would be the slowest and most invasive approach by far. Performance loss could be mitigated by patching the constructor, and using Dynamic Properties to cache a boolean switch for each instance. At least then, it would only by a cost at startup.

**Comment by Fireztonez** [comment]
Okay I see,
It sound lot more complex than what I had anticipated. Clearly the more logical way to do would be hacking the shader, but since the game are still under active development everything can still change at any time.

The idea of moving the layer above 1024 Y can be good I imagine. This sound like a solution not too expensive and simple to do, if that fixed the issue. This might be the also the lightest way to do and render cost should not be affected really.

The `BlenderFloat` solution seam in my mind lot more complex and heavy, but if you manage to reduce the cost, did this will make it less heavy question of rendering or it would be the same? When you say cost at startup, you talk when you start the game or when you apply the change I imagine? This is probably not really a big issue in that case, but is it worth doing that way, since it look soo much more complex?

**Comment by ApacheTech** [comment]
I'm literally just now uploading a new version with a hotfix. I'm hoping this will solve it for you.

I went with a shader uniform override, which works flawlessly for the scenarios within my test world (forced weather effects at different Y heights, climate regions, times, seasons). Because it's set at a shader level, it should update more often, and therefore hold it's values.

```
Update to 2.3.1 (Hotfix):

 - Fixed: Mist Effect now disabled at the shader uniform level, to hopefully fix issues when loading and unloading climate regions.

 - Fixed: Sound Effects GUI now maintains list filters and sort orders when confirming changes to sound effects.
```
