### ISSUE TITLE
[FEATURE] Ability to turn off the shaking of an item in hand

### ISSUE THREAD

**Issue by Orome453** [ApacheTechSolutions/ApacheTech.VintageMods.AccessibilityTweaks#6]
When I play the game, I feel very uncomfortable because of the shaking effect, this mod helped me, but the game still has the effect of shaking the item in your hand when you walk. This causes discomfort, so I want to add a function to disable the shaking of the item in the player's hand when you move.

**Comment by ApacheTech** [comment]
Feature implemented in upcoming release, v3.0.0
